# Random Forest IMplementation

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=load_iris()

In [ ]:
data

In [ ]:
X=data.data
Y=data.target
columns=data.feature_names

In [ ]:
type(X)

In [ ]:
df=pd.DataFrame(data=X,columns=columns)

In [ ]:
df

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df,Y, test_size=0.2, random_state=42, stratify=Y)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,Y_train)
Y_predict=model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
s1=accuracy_score(Y_test,Y_predict)

In [ ]:
s1

In [ ]:
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of trees
    'max_depth': [None, 10, 20],     # Max depth of trees
    'min_samples_split': [2, 5, 10], # Min samples required to split
    'min_samples_leaf': [1, 2, 4]    # Min samples per leaf
}

In [ ]:
from sklearn.model_selection import GridSearchCV
model2=GridSearchCV(model,param_grid)



In [ ]:
model2.fit(X_train,Y_train)

In [ ]:
Y_pred=model2.predict(X_test)
Y_pred

In [ ]:
score2=accuracy_score(Y_test,Y_pred)

In [ ]:
score2

In [ ]:
best_model = model2.best_estimator_

In [ ]:
best_model.feature_importances_

# Feature Importance using random Forest and new dataset

In [ ]:
model.feature_importances_

In [ ]:
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
X,y=make_classification(n_samples=5,n_classes=2,n_features=2,n_informative=2,n_redundant=0,random_state=0)

In [ ]:
X

In [ ]:
y

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(X,y)

In [ ]:
from sklearn.tree import plot_tree
plot_tree(clf)

In [ ]:
clf.feature_importances_ # sum of importance=1

# KNN classifier Implementation

In [43]:
import seaborn as sns
from seaborn import load_dataset

In [44]:
df=load_dataset("iris")

In [45]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [46]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
print(x)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [47]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [49]:
x_train

sepal_length  sepal_width  petal_length  petal_width
4             5.0          3.6           1.4          0.2
32            5.2          4.1           1.5          0.1
142           5.8          2.7           5.1          1.9
85            6.0          3.4           4.5          1.6
86            6.7          3.1           4.7          1.5
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[112 rows x 4 columns]

In [50]:
sc=StandardScaler()

In [51]:
sc.fit_transform(x_train)

array([[-1.01827123,  1.2864604 , -1.39338902, -1.3621769 ],
       [-0.7730102 ,  2.43545215, -1.33550342, -1.49647603],
       [-0.03722712, -0.78172474,  0.74837808,  0.92090833],
       [ 0.20803391,  0.8268637 ,  0.4010645 ,  0.51801093],
       [ 1.06644751,  0.13746866,  0.51683569,  0.3837118 ],
       [-0.52774918,  1.97585545, -1.45127462, -1.09357864],
       [-0.52774918,  1.51625875, -1.33550342, -1.3621769 ],
       [-0.40511866, -1.47111979, -0.06202028, -0.28778385],
       [ 0.57592545, -0.55192639,  0.74837808,  0.3837118 ],
       [ 0.69855596,  0.13746866,  0.97992047,  0.7866092 ],
       [ 0.94381699, -0.09232969,  0.3431789 ,  0.24941267],
       [ 1.67960008,  1.2864604 ,  1.32723405,  1.72670311],
       [-0.15985763, -0.32212804,  0.2274077 ,  0.11511354],
       [ 2.17012213, -0.09232969,  1.61666204,  1.18950659],
       [-0.28248815, -0.09232969,  0.4010645 ,  0.3837118 ],
       [-0.89564072,  1.05666205, -1.39338902, -1.3621769 ],
       [ 2.29275265, -0.

In [52]:
sc.transform(x_test)

array([[ 0.33066442, -0.55192639,  0.51683569, -0.01918559],
       [-0.15985763,  1.7460571 , -1.21973223, -1.22787777],
       [ 2.29275265, -1.01152309,  1.79031883,  1.45810485],
       [ 0.20803391, -0.32212804,  0.4010645 ,  0.3837118 ],
       [ 1.18907802, -0.55192639,  0.57472129,  0.24941267],
       [-0.52774918,  0.8268637 , -1.33550342, -1.09357864],
       [-0.28248815, -0.32212804, -0.11990588,  0.11511354],
       [ 1.31170853,  0.13746866,  0.74837808,  1.45810485],
       [ 0.45329494, -1.93071649,  0.4010645 ,  0.3837118 ],
       [-0.03722712, -0.78172474,  0.05375091, -0.01918559],
       [ 0.82118648,  0.367267  ,  0.74837808,  1.05520746],
       [-1.26353226, -0.09232969, -1.39338902, -1.49647603],
       [-0.40511866,  1.05666205, -1.45127462, -1.3621769 ],
       [-1.14090175,  0.13746866, -1.33550342, -1.49647603],
       [-0.89564072,  1.7460571 , -1.33550342, -1.22787777],
       [ 0.57592545,  0.59706535,  0.51683569,  0.51801093],
       [ 0.82118648, -0.

In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
classifier=KNeighborsClassifier()

In [55]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': range(1, 30)}
grid_search = GridSearchCV(classifier, param_grid, cv=5)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 30)})

In [56]:
grid_search.best_estimator_

KNeighborsClassifier(n_neighbors=4)

In [57]:
grid_search.best_params_

{'n_neighbors': 4}

In [58]:
y_pred=grid_search.predict(x_test)
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa'], dtype=object)

In [59]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

1.0

In [61]:
from sklearn.metrics import classification_report
class_report=classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [62]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
