In [1]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1.shape)
a2=a1.reshape(3,3)
print(a2.shape)
mean1=np.mean(a1)
print("a1 mean: ",mean1)
mean2=np.mean(a2)
print("a2 mean: ",mean2)
median1=np.median(a1)
print("median of a1: ",median1)

(9,)
(3, 3)
a1 mean:  5.0
a2 mean:  5.0
median of a1:  5.0


In [2]:
np.unique(a1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2=a1.astype(
    float
)

In [4]:
a2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
import pandas as pd
df=pd.DataFrame({"A": [1,2,3,4,5,6],"B":[9,8,7,6,5,4]})
df

A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5
5  6  4

In [6]:
df["Squared"]=df["A"].apply(lambda x: x**2)
df

A  B  Squared
0  1  9        1
1  2  8        4
2  3  7        9
3  4  6       16
4  5  5       25
5  6  4       36

In [7]:
df["MEan"]=df.groupby("B")["A"].transform("mean")
df

A  B  Squared  MEan
0  1  9        1   1.0
1  2  8        4   2.0
2  3  7        9   3.0
3  4  6       16   4.0
4  5  5       25   5.0
5  6  4       36   6.0

In [8]:
df1=pd.DataFrame([[1,2,3,4,5],[2,3,4,5,6]])
df1

0  1  2  3  4
0  1  2  3  4  5
1  2  3  4  5  6

In [9]:
df2=pd.DataFrame({"A":[10,11,12,13]})

In [10]:
df3=pd.concat([df,df1])
df3

A    B  Squared  MEan    0    1    2    3    4
0  1.0  9.0      1.0   1.0  NaN  NaN  NaN  NaN  NaN
1  2.0  8.0      4.0   2.0  NaN  NaN  NaN  NaN  NaN
2  3.0  7.0      9.0   3.0  NaN  NaN  NaN  NaN  NaN
3  4.0  6.0     16.0   4.0  NaN  NaN  NaN  NaN  NaN
4  5.0  5.0     25.0   5.0  NaN  NaN  NaN  NaN  NaN
5  6.0  4.0     36.0   6.0  NaN  NaN  NaN  NaN  NaN
0  NaN  NaN      NaN   NaN  1.0  2.0  3.0  4.0  5.0
1  NaN  NaN      NaN   NaN  2.0  3.0  4.0  5.0  6.0

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
import seaborn as sns

In [13]:
from seaborn import load_dataset

In [14]:
df=load_dataset("iris")

In [15]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
x=df[["sepal_length"]]
y=df.iloc[:,1]


In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,random_state=42,test_size=0.2)


In [18]:
model=LinearRegression()

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc=StandardScaler()

In [21]:
x_scaled=sc.fit_transform(X_train)

In [22]:
model.fit(x_scaled,Y_train)

LinearRegression()

In [23]:
X_test=sc.transform(X_test)
y_pred=model.predict(X_test)

In [24]:
from sklearn.metrics import r2_score,mean_squared_error

In [25]:
score=r2_score(Y_test,y_pred)
print(score)
score1=mean_squared_error(Y_test,y_pred)
print(score1)

0.02409862647397254
0.1396189565057903


In [26]:
from sklearn.linear_model import Ridge

In [27]:
ridge=Ridge(alpha=0.5)

In [28]:
ridge.fit(x_scaled,Y_train)

Ridge(alpha=0.5)

In [29]:
y_pred1=ridge.predict(X_test)

In [30]:
score3=r2_score(Y_test,y_pred1)
score3

0.02405563072185468

In [31]:
from sklearn.linear_model import Lasso
df=load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [32]:
x=df[["sepal_length"]]
y=df.iloc[:,1]
x

sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [33]:
y

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)


In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

In [37]:
x_test=sc.transform(x_test)

In [38]:
model=Lasso()
model.fit(x_train,y_train)

Lasso()

In [39]:
y_pred=model.predict(x_test)
y_pred

array([3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667,
       3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667,
       3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667,
       3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667,
       3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667,
       3.06166667, 3.06166667, 3.06166667, 3.06166667, 3.06166667])

In [40]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

-0.0032812985399190975

In [41]:
from sklearn.metrics import root_mean_squared_error

In [42]:
root_mean_squared_error(y_test,y_pred)

0.37886159888686405

In [44]:
from sklearn.metrics import accuracy_score

In [ ]:
score=accuracy_score()